name: Create Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # optional but recommended

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: --openssl-legacy-provider   # ← Best place for this
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build project
              run: |
                  npm install --force
                  npm run build

            - name: Install Composer dependencies
              run: composer install --no-dev --optimize-autoloader

            - name: Zip Folder
              run: |
                  zip -r 99forms.zip . -x ".git/*" ".github/*" "node_modules/*" "src/*" ".vscode/*" ".editorconfig" ".eslintrc.json" ".gitignore" "composer.json" "composer.lock" "package.json" "package-lock.json" "phpcs.xml"

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: 99forms.zip